export const GENRES = [
  { id: 1172, name: '4-Koma' },
  { id: 9, name: 'Action' },
  { id: 2205, name: 'Adult' },
  { id: 12, name: 'Adventure' },
  { id: 4274, name: 'Cartoon' },
  { id: 4, name: 'Comedy' },
  { id: 160, name: 'Completed' },
  { id: 617, name: 'Cooking' },
  { id: 2724, name: 'Crime' },
  { id: 3021, name: 'Cultivation' },
  { id: 2642, name: 'Demon' },
  { id: 121, name: 'Demons' },
  { id: 2615, name: 'Doujinshi' },
  { id: 15, name: 'Drama' },
  { id: 17, name: 'Ecchi' },
  { id: 5, name: 'Fantasy' },
  { id: 3120, name: 'Full color' },
  { id: 19, name: 'Game' },
  { id: 25, name: 'Gender Bender' },
  { id: 2753, name: 'Gore' },
  { id: 56, name: 'Harem' },
  { id: 113, name: 'Historical' },
  { id: 2875, name: 'Horor' },
  { id: 24, name: 'Horror' },
  { id: 3958, name: 'Incest' },
  { id: 135, name: 'Isekai' },
  { id: 96, name: 'Magic' },
  { id: 3299, name: 'Manga' },
  { id: 10, name: 'Manhua' },
  { id: 208, name: 'Manhwa' },
  { id: 73, name: 'Martial Art' },
  { id: 128, name: 'Martial Arts' },
  { id: 2635, name: 'Mature' },
  { id: 57, name: 'Mecha' },
  { id: 58, name: 'Medical' },
  { id: 107, name: 'Military' },
  { id: 2851, name: 'Monster' },
  { id: 59, name: 'Monster Girls' },
  { id: 2649, name: 'Monsters' },
  { id: 2650, name: 'Music' },
  { id: 2613, name: 'Mystery' },
  { id: 18, name: 'N/A' },
  { id: 3158, name: 'One Shot' },
  { id: 171, name: 'Oneshot' },
  { id: 1674, name: 'Police' },
  { id: 93, name: 'post-apocalyptic' },
  { id: 4047, name: 'Psychological' },
  { id: 62, name: 'Reincarnation' },
  { id: 2443, name: 'Reverse Harem' },
  { id: 2629, name: 'Romance' },
  { id: 14, name: 'Samurai' },
  { id: 2630, name: 'Josei' },
  { id: 21, name: 'School' },
  { id: 64, name: 'School Life' },
  { id: 20, name: 'Sci-Fi' },
  { id: 7, name: 'Seinen' },
  { id: 2916, name: 'Shotacon' },
  { id: 16, name: 'Shoujo' },
  { id: 169, name: 'Shoujo Ai' },
  { id: 11, name: 'Shounen' },
  { id: 195, name: 'Shounen ai' },
  { id: 65, name: 'Slice of Life' },
  { id: 3089, name: 'Smut' },
  { id: 22, name: 'Sports' },
  { id: 13, name: 'Super Power' },
  { id: 6, name: 'Supernatural' },
  { id: 213, name: 'Thriller' },
  { id: 2530, name: 'Time Travel' },
  { id: 66, name: 'Tragedy' },
  { id: 83, name: 'Vampire' },
  { id: 3121, name: 'Video games' },
  { id: 3122, name: 'Virtual reality' },
  { id: 2603, name: 'Webtoon' },
  { id: 165, name: 'Webtoons' },
  { id: 200, name: 'Yaoi' },
  { id: 115, name: 'Yuri' },
  { id: 2518, name: 'Zombies' }
]
